apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer #NodePort 
  ports:
    - port: 9000
    # - protocol: TCP
    #   port: 9000
    #   nodePort: 30080
  selector:
    app: app